apiVersion: apps/v1
kind: Deployment
metadata:
  name: mychart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mychart
  template:
    metadata:
      labels:
        app: mychart
    spec:
      containers:
        - name: my-container
          image: juank8sclusteracr.azurecr.io/node-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: TITLE
              value: 'AKS Ingress Demo 01'
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
      nodeSelector:
        nodePoolType: user
---
apiVersion: v1
kind: Service
metadata:
  name: mychart-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: mychart
