# save the original value of .
{{- $top := . -}}
{{- $fullName := include "test-chart.fullname" . -}}
# iterate over the ingress configurations
{{- range $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName}}-{{ $deployment.name }}
spec:
  {{- if not $top.Values.autoscaling.enabled }}
  replicas: {{ $deployment.replicas }}
  {{- end}}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
  template:
    metadata:
      labels:
        app: {{ $deployment.name }}
    spec:
      containers:
        - name: {{ $top.Chart.Name }}
          image: {{ $top.Values.image.repository }}:{{ $top.Values.image.tag }}
          imagePullPolicy: {{ $top.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $top.Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $top.Values.resources | nindent 12 }}     
      {{- with $top.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}